// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://pseekvwhfhzwlcaloger.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InBzZWVrdndoZmh6d2xjYWxvZ2VyIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzUyMTUxOTcsImV4cCI6MjA5MDc5MTE5N30.o1Y1HZ0RdtRimOfkHY8ubhIfqm6Foa96WL_-3PQVPk0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});